name: Sync to KhoiTran1999

on:
  push:
    branches: [ "main" ]

jobs:
  sync-repo:
    if: github.repository == 'khoitran200199-lab/telegram_stock_bot_anotherAccount'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to KhoiTran1999
        env:
          API_TOKEN: ${{ secrets.API_TOKEN_GITHUB_B }}
        run: |
          git config --global user.email "khoitran200199@gmail.com"
          git config --global user.name "khoitran200199-lab"
          
          # QUAN TRỌNG: Xóa header auth mặc định do actions/checkout tạo ra
          # Để tránh việc nó tự động dùng github-actions[bot]
          git config --unset-all http.https://github.com/.extraheader || true
          
          # Gán URL mới có chứa Token trực tiếp vào remote 'origin'
          git remote set-url origin https://KhoiTran1999:$API_TOKEN@github.com/KhoiTran1999/telegram_stock_bot.git
          
          # Push thẳng (lúc này origin đã chứa token rồi nên không cần điền lại)
          git push origin main --force
