name: Sync to KhoiTran1999

on:
  push:
    branches: [ "main" ]

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to KhoiTran1999
        env:
          API_TOKEN: ${{ secrets.API_TOKEN_GITHUB_B }}
        run: |
          git config --global user.email "khoitran200199@gmail.com"
          git config --global user.name "khoitran200199-lab"
          
          # Dùng cú pháp x-access-token để an toàn nhất
          git push https://x-access-token:$API_TOKEN@github.com/KhoiTran1999/telegram_stock_bot.git main --force
